#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.

# Declare the max number of expected arguments on the command line in a variable "ARGS".
declare -i ARGS="$#"
if [ "$ARGS" -lt 4 ];
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
